---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu2004
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
    systemd: true
    tmpfs:
    - /run
    - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
  - name: ubuntu2204
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    systemd: true
    tmpfs:
    - /run
    - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
  - name: debian10
    image: docker.io/geerlingguy/docker-debian10-ansible
    pre_build_image: true
    systemd: true
    tmpfs:
    - /run
    - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/sbin/init"
  - name: debian11
    image: docker.io/geerlingguy/docker-debian11-ansible
    pre_build_image: true
    systemd: true
    tmpfs:
    - /run
    - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/sbin/init"
  - name: el8
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
    systemd: true
    tmpfs:
    - /run
    - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
  - name: el9
    image: registry.access.redhat.com/ubi9/ubi-init
    pre_build_image: true
    systemd: true
    tmpfs:
    - /run
    - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
provisioner:
  name: ansible
  env:
    ANSIBLE_LOCAL_TEMP: "${HOME}/.ansible/tmp"
    ANSIBLE_REMOTE_TMP: /tmp/ansible
verifier:
  name: ansible

...
